### ISSUE TITLE
Patient profile creation

### ISSUE THREAD

**Issue by flexplicateur** [boyle/2018-measure-stress#19]
Users should be able to create a new patient profile within the application. This can likely be done with a form. Fields to be collected will be specified in a JSON document and rendered as input boxes, radio buttons, etc.

**Comment by fcharih** [comment]
What is useful information that might be worth storing in a patient profile?

**Comment by boyle** [comment]
- reason for referral = **diagnoses** (chronic pain, post traumatic stress, brain injury) + **severity**

- **height** + **weight** ( = estimate BMI, validate force plate/3d point cloud geometry... in theory we can calculate these from the instrumentation)

- heart condition (any previous heart diagnoses which might affect interpretation of the heart beat data)

Should this information be stored in the "user" configuration or with the patient data? If with the user data, it could be stored as a JSON file per patient (e.g. p12.json).
(Currently there is no place to put "common" patient data between sessions.)

**Comment by fcharih** [comment]
Ideally, it would be in a file for data that is persistent for a patient across sessions. That would be ideal. Otherwise, we can also store it in the suggested format "patient_1234.json" in the user's directory as you suggest. Let's go with that for now. These files will live alongside the config.json file.

**Comment by boyle** [comment]
Sounds good. We can migrate later, if that makes sense. This method does facilitate looking up a list of patient numbers for a user: they can look at the JSON files in the user config dir that match a particular pattern: p[0-9]+.json

**Comment by flexplicateur** [comment]
Not an issue.
