### ISSUE TITLE
SSL Certificate not trusted

### ISSUE THREAD

**Issue by fcharih** [boyle/2018-measure-stress#21]
It appears that the Let's Encrypt SSL Certificate is not trusted when requests are made outside of the browser. I experience issues with both ```curl``` and inside the app when I make requests at the login endpoint.

Output of a cURL request:
```
$ curl 'https://saans.ca/auth/login' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
-H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3'\
-H 'Content-Type: application/x-www-form-urlencoded' \
--data 'username=fcharih&password=<mypassword>'

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by fcharih** [comment]
This seems relevant:
https://community.letsencrypt.org/t/some-browser-say-certificate-is-not-trusted/28766/7

**Comment by boyle** [comment]
https://github.com/galeone/letsencrypt-lighttpd
The hint for me:
missing 
`ssl.ca-file = "/etc/lighttpd/fullchain.pem"`
